# Generated by Django 2.1.5 on 2019-02-06 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sexos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pokemons',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='pokemons',
            name='ataque',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemons',
            name='ataqueSp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemons',
            name='defesa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemons',
            name='defesaSp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemons',
            name='descrição',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pokemons',
            name='id_evolucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.Pokemons'),
        ),
        migrations.AddField(
            model_name='pokemons',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pokemons',
            name='velocidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemons',
            name='vida',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemons',
            name='nome',
            field=models.CharField(max_length=15),
        ),
        migrations.AddField(
            model_name='pokemons',
            name='categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pokedex.Categoria'),
        ),
        migrations.AddField(
            model_name='pokemons',
            name='fraquezas',
            field=models.ManyToManyField(related_name='fraquezas', to='pokedex.Tipos'),
        ),
        migrations.AddField(
            model_name='pokemons',
            name='habilidades',
            field=models.ManyToManyField(to='pokedex.Habilidades'),
        ),
        migrations.AddField(
            model_name='pokemons',
            name='sexo',
            field=models.ManyToManyField(to='pokedex.Sexos'),
        ),
        migrations.AddField(
            model_name='pokemons',
            name='tipos',
            field=models.ManyToManyField(related_name='tipos', to='pokedex.Tipos'),
        ),
    ]
