# Generated by Django 2.1.7 on 2019-02-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_auto_20190217_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemons',
            old_name='id_evolucao',
            new_name='poke_evolucao',
        ),
    ]
